modLoader="javafml"
loaderVersion="[36,)"
license="https://www.gnu.org/licenses/lgpl-3.0.en.html"
issueTrackerURL=""
[[mods]]
modId="resourcefulspiders"
version="${file.jarVersion}"
displayName="Resourceful Spiders"
displayURL=""
logoFile="logo.png"
credits="Dawn Felstar helped"
authors="Mikenyes"
description="todo"

[[dependencies.resourcefulspiders]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.resourcefulspiders]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"